-- Bronze = raw append-only landing with metadata
USE WAREHOUSE GOPHER_WH;
USE DATABASE GOPHER_DB;
CREATE SCHEMA IF NOT EXISTS DEMO_BRONZE;
USE SCHEMA DEMO_BRONZE;
/*
DROP TABLE IF EXISTS STREAM_SESSION_RAW;
DROP TABLE IF EXISTS ENGAGEMENT_RAW;
DROP TABLE IF EXISTS SEARCH_RAW;
DROP TABLE IF EXISTS BROWSE_RAW;
DROP TABLE IF EXISTS TILE_IMPR_RAW;
DROP TABLE IF EXISTS COMMERCE_RAW;
DROP TABLE IF EXISTS NOTIFICATION_RAW;*/
-- Canonical shape for each topic: DATA + ingestion metadata
/*
CREATE TABLE IF NOT EXISTS STREAM_SESSION_RAW (
  DATA           VARIANT,
  INGESTED_AT    TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
  SRC_TOPIC      STRING,
  SRC_PARTITION  INTEGER,
  SRC_OFFSET     NUMBER
);

CREATE TABLE ENGAGEMENT_RAW      LIKE STREAM_SESSION_RAW;
CREATE TABLE SEARCH_RAW          LIKE STREAM_SESSION_RAW;
CREATE TABLE BROWSE_RAW          LIKE STREAM_SESSION_RAW;
CREATE TABLE TILE_IMPR_RAW       LIKE STREAM_SESSION_RAW;
CREATE TABLE COMMERCE_RAW        LIKE STREAM_SESSION_RAW;
CREATE TABLE NOTIFICATION_RAW    LIKE STREAM_SESSION_RAW;*/
SELECT
    TABLE_NAME,
    ROW_COUNT
FROM
    INFORMATION_SCHEMA.TABLES
WHERE
    TABLE_SCHEMA = 'DEMO_BRONZE'
    AND TABLE_NAME LIKE '%RAW%'
ORDER BY
    TABLE_NAME;

SELECT
    *
from
    ENGAGEMENT_RAW
LIMIT
    1;

    
CREATE STREAM STREAM_SESSION_RAW_BF ON TABLE STREAM_SESSION_RAW APPEND_ONLY = TRUE SHOW_INITIAL_ROWS = TRUE;
CREATE STREAM ENGAGEMENT_RAW_BF ON TABLE ENGAGEMENT_RAW APPEND_ONLY = TRUE SHOW_INITIAL_ROWS = TRUE;
CREATE STREAM SEARCH_RAW_BF ON TABLE SEARCH_RAW APPEND_ONLY = TRUE SHOW_INITIAL_ROWS = TRUE;
CREATE STREAM BROWSE_RAW_BF ON TABLE BROWSE_RAW APPEND_ONLY = TRUE SHOW_INITIAL_ROWS = TRUE;
CREATE STREAM TILE_IMPR_RAW_BF ON TABLE TILE_IMPR_RAW APPEND_ONLY = TRUE SHOW_INITIAL_ROWS = TRUE;
CREATE STREAM COMMERCE_RAW_BF ON TABLE COMMERCE_RAW APPEND_ONLY = TRUE SHOW_INITIAL_ROWS = TRUE;
CREATE STREAM NOTIFICATION_RAW_BF ON TABLE NOTIFICATION_RAW APPEND_ONLY = TRUE SHOW_INITIAL_ROWS = TRUE;
